ImageServer/Controllers/DownloadReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using ImageServer.Models;

namespace ImageServer.Controllers
{
    [Authorize(Roles = "Provider")]

    public class DownloadReportController : BaseController
    {
        // GET: DownloadReport
        public ActionResult Index()
        {
            List<DownLoadcount> dlc = db.Getuserdownloadedimage(User.Identity.GetUserId());
            return View(dlc);
        }
        
        [HttpPost]
       public ActionResult Index(string startdate, string enddate)
        {
            List<DownLoadcount> dlc = db.Getuserdownloadedimage(User.Identity.GetUserId(),Convert.ToDateTime(startdate), Convert.ToDateTime(enddate));
            return View(dlc);
        }
    }
}

ImageServer/Controllers/ModerateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImageServer.Controllers
{
    [Authorize(Roles = "Moderator")]
    public class ModerateController : BaseController
    {

        // GET: Moderate
        public ActionResult Index()
        {
            List<ImageUpload> mi = db.GetUnmoderatedImages();
            return View(mi);
        }

        // GET: Moderate
        [HttpPost]
        public ActionResult Index(string submit, int? imageid, string tags)
        {
           return View(db.UpdateModeratedImage(imageid.Value, submit, tags));
        }


    }
}

ImageServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.IsInRole("Provider"))
                    {
                    <li>@Html.ActionLink("Upload", "Index", "Upload")</li>
                    }

                    @if (User.IsInRole("Provider"))
                    {
                        <li>@Html.ActionLink("Download Report", "Index", "DownloadReport")</li>
                    }
                    @if (User.IsInRole("Moderator"))
                    {
                        <li>@Html.ActionLink("Moderate Images", "Index", "Moderate")</li>
                    }
                   
                    @if (User.IsInRole("Administrator"))
                    {
                        <li>@Html.ActionLink("Manage & Upload Images", "Index", "ManageImage")</li>
                    }
                    @if (User.IsInRole("Administrator"))
                    {
                        <li>@Html.ActionLink("Manage Users", "Index", "ManageUsers")</li>
                    }
                    @if (User.IsInRole("Consumer"))
                    {
                        <li>@Html.ActionLink("Search Images", "Index", "Consumer")</li>
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CSI3304 Software Development Framework. All rights reserved to Lydia & Jordan </p>
        </footer>
    </div>

   
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>